name: bike_shoping_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_neumorphic_plus: ^3.4.0
  flutter_riverpod: ^2.6.1
  shimmer: ^3.0.0
  json_annotation: ^4.9.0
  flutter_cube: ^0.1.1
  model_viewer_plus: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  ios: true
  android: true
  image_path: "assets/applogo/logo.png"
  flutter_lints: ^4.0.0
  riverpod: ^2.6.1
  json_serializable: ^6.9.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/retro__bike.glb
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
